name: marketbridge_mobile
description: Nigeria's first escrow-powered campus marketplace.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Routing
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  
  # Backend
  supabase_flutter: ^2.4.1
  
  # UI & Theming
  google_fonts: ^6.2.1
  lucide_icons: ^0.1.2
  flutter_animate: ^4.5.0
  cached_network_image: ^3.3.1
  
  # Forms & Payments
  flutter_form_builder: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
