import React from 'react';
import { createServerClient } from "@supabase/ssr"
import { cookies } from "next/headers"
import { redirect } from "next/navigation"
import { Clock, Filter, MessageSquare, Tag, User as UserIcon } from "lucide-react"

// Types
type Feedback = {
  id: string;
  type: string;
  description: string;
  name: string | null;
  email: string | null;
  status: string;
  created_at: string;
}

export const dynamic = "force-dynamic"

export default async function AdminFeedbackPage({
  searchParams,
}: {
  searchParams: { filter?: string }
}) {
  const cookieStore = cookies()
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value
        },
      },
    }
  )

  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    redirect('/portal/login')
  }

  // Double check admin role
  const { data: profile } = await supabase
    .from('users')
    .select('role')
    .eq('id', user.id)
    .single()

  if (!profile || !['operations_admin', 'admin', 'technical_admin', 'marketing_admin', 'ceo', 'cofounder'].includes(profile.role)) {
    redirect('/marketplace')
  }

  const activeFilter = searchParams.filter || 'All'

  // Fetch feedbacks
  let query = supabase
    .from('feedbacks')
    .select('*')
    .order('created_at', { ascending: false })

  if (activeFilter !== 'All') {
    query = query.eq('type', activeFilter)
  }

  // It's possible the table isn't created yet or empty, handle data safely
  const { data: rawFeedbacks, error } = await query
  const feedbacks = (rawFeedbacks as Feedback[]) || []

  const metrics = [
    { label: 'Total Bugs', count: feedbacks.filter(f => f.type === 'Bug Report').length, color: 'text-red-500', bg: 'bg-red-50 dark:bg-red-500/10 border-red-200 dark:border-red-900/50' },
    { label: 'Feature Ideas', count: feedbacks.filter(f => f.type === 'Feature Suggestion').length, color: 'text-blue-500', bg: 'bg-blue-50 dark:bg-blue-500/10 border-blue-200 dark:border-blue-900/50' },
    { label: 'Transactions', count: feedbacks.filter(f => f.type === 'Transaction Issue').length, color: 'text-amber-500', bg: 'bg-amber-50 dark:bg-amber-500/10 border-amber-200 dark:border-amber-900/50' },
    { label: 'Total Feedbacks', count: feedbacks.length, color: 'text-zinc-900 dark:text-zinc-100', bg: 'bg-zinc-50 dark:bg-zinc-800/40 border-zinc-200 dark:border-zinc-800' }
  ]

  const filters = ['All', 'Bug Report', 'Feature Suggestion', 'Transaction Issue', 'General Feedback']

  return (
    <main className="p-8 pb-32">
      <div className="max-w-6xl mx-auto space-y-8">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div>
            <h1 className="text-3xl font-black text-zinc-900 dark:text-white tracking-tight">Beta Feedback</h1>
            <p className="text-sm font-medium text-zinc-500 dark:text-zinc-400 mt-1">Live platform reports generated by buyers and sellers across campus.</p>
          </div>
        </div>

        {error && (
          <div className="p-4 bg-red-50 dark:bg-red-950/20 text-red-600 dark:text-red-400 border border-red-200 dark:border-red-900/50 rounded-xl text-sm font-bold">
            Database access error or table missing. Connect to database to verify `feedbacks` schema.
          </div>
        )}

        {/* Metrics Row */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {metrics.map(m => (
            <div key={m.label} className={`p-5 rounded-2xl border flex flex-col gap-1 ${m.bg}`}>
               <span className="text-xs font-bold uppercase tracking-wider text-zinc-500">{m.label}</span>
               <span className={`text-3xl font-black ${m.color}`}>{m.count}</span>
            </div>
          ))}
        </div>

        {/* Filters */}
        <div className="flex flex-wrap items-center gap-2">
          {filters.map(f => {
            const isActive = activeFilter === f;
            return (
              <a 
                key={f}
                href={`?filter=${f}`}
                className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-xl border transition-all ${
                  isActive 
                  ? 'bg-zinc-900 border-zinc-900 text-white dark:bg-white dark:border-white dark:text-zinc-950' 
                  : 'bg-white border-zinc-200 text-zinc-600 dark:bg-zinc-950 dark:border-zinc-800 dark:text-zinc-400 hover:bg-zinc-50 dark:hover:bg-zinc-900'
                }`}
              >
                {f}
              </a>
            )
          })}
        </div>

        {/* Feedbacks Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
          {feedbacks.map(f => (
            <div key={f.id} className="bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow relative overflow-hidden group">
               {/* Accent strip */}
               <div className={`absolute top-0 left-0 w-1.5 h-full ${
                 f.type === 'Bug Report' ? 'bg-red-500' :
                 f.type === 'Feature Suggestion' ? 'bg-blue-500' :
                 f.type === 'Transaction Issue' ? 'bg-amber-500' : 'bg-emerald-500'
               }`} />

               <div className="flex items-center justify-between mb-4 ml-2">
                 <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[10px] uppercase tracking-wider font-black ${
                   f.type === 'Bug Report' ? 'bg-red-50 text-red-600 dark:bg-red-500/10' :
                   f.type === 'Feature Suggestion' ? 'bg-blue-50 text-blue-600 dark:bg-blue-500/10' :
                   f.type === 'Transaction Issue' ? 'bg-amber-50 text-amber-600 dark:bg-amber-500/10' : 'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10'
                 }`}>
                   <Tag className="h-3 w-3" />
                   {f.type}
                 </span>
                 <span className="text-xs font-semibold text-zinc-400 flex items-center gap-1">
                   <Clock className="h-3 w-3" />
                   {new Date(f.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit'})}
                 </span>
               </div>

               <p className="text-sm font-medium text-zinc-700 dark:text-zinc-300 leading-relaxed ml-2 mb-6">
                 "{f.description}"
               </p>

               <div className="mt-auto ml-2 flex items-center gap-3 pt-4 border-t border-zinc-100 dark:border-zinc-800/50">
                 <div className="h-8 w-8 rounded-full bg-zinc-100 dark:bg-zinc-900 flex items-center justify-center border border-zinc-200 dark:border-zinc-800">
                    <UserIcon className="h-4 w-4 text-zinc-400" />
                 </div>
                 <div className="flex flex-col">
                   <span className="text-xs font-bold text-zinc-900 dark:text-white truncate max-w-[200px]">{f.name || 'Anonymous Beta Tester'}</span>
                   {f.email && <span className="text-[10px] font-medium text-zinc-500 truncate max-w-[200px]"><a href={`mailto:${f.email}`} className="hover:underline">{f.email}</a></span>}
                 </div>
               </div>
            </div>
          ))}

          {feedbacks.length === 0 && !error && (
            <div className="col-span-full py-16 flex flex-col items-center justify-center border-2 border-dashed border-zinc-200 dark:border-zinc-800 rounded-3xl">
              <MessageSquare className="h-12 w-12 text-zinc-300 mb-4 animate-pulse" />
              <h3 className="text-lg font-black text-zinc-900 dark:text-white">No feedback matching this filter.</h3>
              <p className="text-sm text-zinc-500 mt-2">Check back later or change your filters.</p>
            </div>
          )}
        </div>

      </div>
    </main>
  )
}
